# Generated by Django 3.2.3 on 2021-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_list',
            name='category',
            field=models.CharField(choices=[('apple', 'apple'), ('orange', 'orange')], default='', max_length=30),
        ),
    ]
