# Generated by Django 3.1.12 on 2021-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept_list', '0002_dept_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_list',
            name='category',
            field=models.CharField(choices=[('', 'apple1'), ('', 'orange')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='dept_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
